from random import randint
from random import randint
import pygame
from pygame.sprite import Sprite

class Pigeon(Sprite):
    """A class to represent a single pigeon in the fleet."""
    def __init__(self, ai_game):
        """Initialize the pigeon and set its starting position."""
        super().__init__()
        self.screen = ai_game.screen
        self.settings = ai_game.settings
        
        # Load the pigeon image and set its rect attribute.
        # -------------------------------------------------------------------
        # This file includes use of a pigeon sprite generated by OpenAI's
        # ChatGPT (DALL·E) and modified. According to OpenAI's policies,
        # the image is free to use for commercial and non-commercial purposes,
        # ChatGPT (DALL·E) and modified. According to OpenAI's policies,
        # the image is free to use for commercial and non-commercial purposes,
        # and does not require attribution. 
        # Source: https://chatgpt.com/c/683c827e-250c-8013-adc1-2d29f2f123d4
        # -------------------------------------------------------------------
        self.image = pygame.image.load('images/pigeon.png').convert_alpha()        
        self.rect = self.image.get_rect()

        # Start each new pigeon at a random position on the right side
        #   of the screen.
        self.rect.left = self.screen.get_rect().right
        # The farthest down the screen we'll place the pigeon is the height
        #   of the screen, minus the height of the pigeon.
        pigeon_top_max = self.settings.screen_height - self.rect.height
        self.rect.top = randint(0, pigeon_top_max)
        # Start each new pigeon at a random position on the right side
        #   of the screen.
        self.rect.left = self.screen.get_rect().right
        # The farthest down the screen we'll place the pigeon is the height
        #   of the screen, minus the height of the pigeon.
        pigeon_top_max = self.settings.screen_height - self.rect.height
        self.rect.top = randint(60, pigeon_top_max)

        # Store the pigeon's exact horizontal position.
        self.x = float(self.rect.x)        
        self.x = float(self.rect.x)        
        
    def update(self):
        """Move the pigeon to the left."""
        self.x -= self.settings.pigeon_speed
        self.rect.x = self.x
        """Move the pigeon to the left."""
        self.x -= self.settings.pigeon_speed
        self.rect.x = self.x